Smartin data utils enhancement
PyICe-ADI/PyICe pull request #7
Opened 2023-10-16 13:41 UTC by xenomorphxx131

Has some data utils enhancements but more importantly bug fixes in lab interfaces that need to get merged.

2023-10-17 15:01 UTC, timlaracy commented
Can you see this?

2023-10-17 15:02 UTC, timlaracy requested changes

2023-10-17 15:08 UTC, xenomorphxx131 commented on PyICe/data_utils/spectrum_analyzer.py
Agreed there should be more docs on the methods there.
Will comply.

For the phase, the point was to emulate a bench spectrum analyzer which I doubt can track phase the way an FFT can.
That said, it might be a useful extension later on if someone wants to reconstruct a time domain waveform.

2023-10-19 13:36 UTC, timlaracy approved these changes

2023-10-19 13:36 UTC, merged